name: Web Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:    

    - name: Checkout
      uses: actions/checkout@v2.3.4
          
    - name: Remove File
      uses: JesseTG/rm@v1.0.0
      with:
        path: README.md
        
    - name: Remove File
      uses: JesseTG/rm@v1.0.0
      with:
        path: .vscode/
        
    - name: Remove File
      uses: JesseTG/rm@v1.0.0
      with:
        path: jsconfig.json
        
    - name: Remove File
      uses: JesseTG/rm@v1.0.0
      with:
        path: screenshot.png
        
    - name: Remove File
      uses: JesseTG/rm@v1.0.0
      with:
        path: ${{ github.event.repository.name }}.code-workspace
          
    - name: Minify
      uses: anthonyftwang/minify-action@v1.0.1
      
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: web
        folder: .
        
        
    - uses: actions/checkout@v2
      with:
         ref: main
          
    - name: Screenshot Website
      uses: swinton/screenshot-website@v1.x
      with:
        width: 1500
        source: https://${{ github.actor }}.github.io/${{ github.event.repository.name }}/
        destination: screenshot.png
        full-page: true
        delay: 120
          
    - uses: actions/download-artifact@v2
      with:
        name: screenshot

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: update screenshot
        branch: main    
        
    - name: Clean
      uses: GeekyEggo/delete-artifact@v1.0.0
      with:
        name: screenshot


